import esbuild from "esbuild";
import process from "process";
import builtins from 'builtin-modules';
import fs from 'fs-extra'; // Using fs-extra for easier copying
import path from 'path';

const banner =
`/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const prod = (process.argv[2] === 'production');
const pluginId = 'simple-note-chat';
const outDir = prod ? '.' : `test-vault/.obsidian/plugins/${pluginId}/`; // Output directly to vault for dev
const outFile = path.join(outDir, 'main.js');
const manifestFile = 'manifest.json';
const hotreloadFile = path.join(outDir, '.hotreload');

// Function to copy manifest and touch hotreload
const copyManifestAndHotreload = async () => {
  try {
    if (!prod) { // Only copy/hotreload in dev mode
      await fs.ensureDir(outDir); // Ensure the target directory exists
      await fs.copy(manifestFile, path.join(outDir, manifestFile));
      await fs.ensureFile(hotreloadFile); // Touch the .hotreload file
      console.log('Manifest copied and .hotreload touched.');
    }
  } catch (err) {
    console.error('Error during post-build steps:', err);
  }
};

const context = await esbuild.context({
  banner: {
    js: banner,
  },
  entryPoints: ['src/main.ts'],
  bundle: true,
  external: [
    'obsidian',
    'electron',
    '@codemirror/autocomplete',
    '@codemirror/collab',
    '@codemirror/commands',
    '@codemirror/language',
    '@codemirror/lint',
    '@codemirror/search',
    '@codemirror/state',
    '@codemirror/view',
    '@lezer/common',
    '@lezer/highlight',
    '@lezer/lr',
    ...builtins
  ],
  format: 'cjs',
  target: 'es2018',
  logLevel: "info",
  sourcemap: prod ? false : 'inline',
  treeShaking: true,
  outfile: outFile,
  plugins: [{
    name: 'on-rebuild-plugin',
    setup(build) {
      // Run initially after the first build
      build.onEnd(async (result) => {
        if (result.errors.length === 0) {
          console.log('Initial build successful.');
          await copyManifestAndHotreload();
        } else {
          console.error('Initial build failed:', result.errors);
        }
      });
    },
  }],
});

if (prod) {
  await context.rebuild(); // Perform a single build for production
  console.log('Production build complete.');
  await context.dispose();
} else {
  // Development mode: watch for changes
  await context.watch();
  console.log(`Watching for changes... Outputting to ${outDir}`);

  // Setup rebuild hook specifically for watch mode
  // This requires re-creating context slightly differently or managing state
  // Simpler approach: The onEnd in the plugin will trigger on each rebuild in watch mode.
  // We just need to ensure copyManifestAndHotreload runs on subsequent builds too.

  // Let's refine the plugin to handle rebuilds correctly in watch mode
  await context.dispose(); // Dispose the previous context

  const watchContext = await esbuild.context({
    banner: { js: banner },
    entryPoints: ['src/main.ts'],
    bundle: true,
    external: [
      'obsidian', 'electron', '@codemirror/autocomplete', '@codemirror/collab',
      '@codemirror/commands', '@codemirror/language', '@codemirror/lint',
      '@codemirror/search', '@codemirror/state', '@codemirror/view',
      '@lezer/common', '@lezer/highlight', '@lezer/lr', ...builtins
    ],
    format: 'cjs',
    target: 'es2018',
    logLevel: "info",
    sourcemap: 'inline',
    treeShaking: true,
    outfile: outFile,
    plugins: [{
      name: 'on-rebuild-watch-plugin',
      setup(build) {
        build.onEnd(async (result) => {
          if (result.errors.length === 0) {
            console.log('Build successful.');
            await copyManifestAndHotreload(); // Run on every successful rebuild
          } else {
            console.error('Build failed:', result.errors);
          }
        });
      },
    }],
  });

  await watchContext.watch();
  console.log(`Watching for changes... Outputting to ${outDir}`);
  // Keep the process running for watch mode
  // process.stdin.resume(); // Not strictly needed if script is run directly
}